import { readdir, readFile, writeFile } from 'fs/promises';
import { join, relative } from 'path';

const PROMPTS_DIR = join(import.meta.dir, '../prompts');
const OUTPUT_FILE = join(PROMPTS_DIR, 'embedded.ts');

async function collectMdFiles(dir: string): Promise<Array<{ path: string; key: string }>> {
  const entries = await readdir(dir, { withFileTypes: true, recursive: true });
  const files: Array<{ path: string; key: string }> = [];

  for (const entry of entries) {
    if (!entry.isFile() || !entry.name.endsWith('.md')) continue;
    const fullPath = join(entry.parentPath ?? dir, entry.name);
    const rel = relative(PROMPTS_DIR, fullPath);
    const key = rel.replace(/\.md$/, '').replace(/[\/\\]/g, '_').replace(/-/g, '_');
    files.push({ path: fullPath, key });
  }
  return files;
}

async function main() {
  const files = await collectMdFiles(PROMPTS_DIR);
  const lines: string[] = ['// Auto-generated by scripts/embed-prompts.ts — do not edit manually', ''];

  for (const file of files.sort((a, b) => a.key.localeCompare(b.key))) {
    const content = await readFile(file.path, 'utf-8');
    const escaped = content.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$');
    lines.push(`export const ${file.key} = \`${escaped}\`;`);
    lines.push('');
  }

  const keys = files.map(f => f.key).sort();
  lines.push(`export const PROMPTS: Record<string, string> = {`);
  for (const key of keys) {
    lines.push(`  ${key},`);
  }
  lines.push('};');
  lines.push('');

  await writeFile(OUTPUT_FILE, lines.join('\n'));
  console.log(`Generated ${OUTPUT_FILE} with ${files.length} prompts`);
}

main().catch(console.error);
